apiVersion: v1
kind: Pod
metadata:
  name: gcp-to-s3-migrator
  labels:
    name: gcp-to-s3-migrator
spec:
  serviceAccountName: gcp-service-account
  containers:
    - name: gcp-to-s3-migrator
      image: ghcr.io/jkoenig134/gcloud-storage-to-s3-migrator:latest
      imagePullPolicy: Always
      resources:
        limits:
          memory: "2Gi"
          cpu: "1000m"
      env:
        - name: S3_ENDPOINT
          value: <todo>
        - name: S3_ACCESS_KEY_ID
          value: <todo>
        - name: S3_SECRET_ACCESS_KEY
          value: <todo>
        - name: S3_BUCKET_NAME
          value: <todo>
        - name: GCLOUD_BUCKET_NAME
          value: <todo>
